import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import TravelAssistant from "@/components/TravelAssistant";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen overflow-x-hidden`}
        >
          <Navbar />
          {children}
          <div className="pointer-events-none">
            <div className="pointer-events-auto">
              <TravelAssistant />
            </div>
          </div>
        </body>
      </html>
    // </ClerkProvider>
  );
}
