import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import {
  ClerkProvider,
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen overflow-x-hidden`}
        >
          <Navbar />
          {children}
          {/* Floating travel assistant */}
          <div className="pointer-events-none">
            {/* wrapper keeps stacking context clean; inner has pointer events */}
            <div className="pointer-events-auto">
              {/* client component */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
            </div>
          </div>
        </body>
      </html>
    // {/* </ClerkProvider> */}
  );
}
